apiVersion: v1
kind: Namespace
metadata:
  name: beryl-fintech
  labels:
    name: beryl-fintech
    domain: fintech
    environment: production
    team: fintech
    cost-center: fintech-operations
spec:
  finalizers:
  - kubernetes