apiVersion: v1
kind: Namespace
metadata:
  name: beryl-social
  labels:
    name: beryl-social
    domain: social
    environment: production
    team: social
    cost-center: social-operations
spec:
  finalizers:
  - kubernetes