global:
  resolve_timeout: 5m

route:
  receiver: bank-regulatory-webhook
  group_by: ["alertname", "severity"]
  group_wait: 20s
  group_interval: 2m
  repeat_interval: 1h

receivers:
  - name: bank-regulatory-webhook
    webhook_configs:
      - url: "http://alert-webhook-simulator:8080/mock-alert-webhook"
        send_resolved: true

inhibit_rules:
  - source_matchers:
      - severity = critical
    target_matchers:
      - severity = warning
    equal: ["alertname", "service"]
